In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
np.concatenate([arr1, arr1], axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [4]:
np.concatenate([arr1, arr1], axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
ser1 = Series([0, 1, 2], index=['T', 'U', 'V'])

ser2 = Series([3, 4], index=['X', 'Y'])

In [7]:
ser1

T    0
U    1
V    2
dtype: int64

In [8]:
ser2

X    3
Y    4
dtype: int64

In [9]:
pd.concat([ser1, ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [10]:
pd.concat([ser1, ser2], axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [11]:
pd.concat([ser1, ser2], keys=['cat1', 'cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [12]:
dframe1 = DataFrame(np.random.randn(4, 3), columns=['X', 'Y', 'Z'])

dframe2 = DataFrame(np.random.randn(3,3), columns=['Y', 'Q', 'X'])


In [13]:
dframe1

X         Y         Z
0 -1.084551 -0.293405 -0.402948
1 -1.543618 -0.403538  0.340821
2  0.295654 -0.754895  1.932140
3  0.387930 -0.397124 -0.430610

In [14]:
dframe2

Y         Q         X
0  1.380461  0.465284 -1.050797
1 -0.397843 -0.110875 -1.216634
2  0.353455 -0.482835  0.209350

In [15]:
pd.concat([dframe1, dframe2])

X         Y         Z         Q
0 -1.084551 -0.293405 -0.402948       NaN
1 -1.543618 -0.403538  0.340821       NaN
2  0.295654 -0.754895  1.932140       NaN
3  0.387930 -0.397124 -0.430610       NaN
0 -1.050797  1.380461       NaN  0.465284
1 -1.216634 -0.397843       NaN -0.110875
2  0.209350  0.353455       NaN -0.482835

In [16]:
pd.concat([dframe1, dframe2], ignore_index=True)

X         Y         Z         Q
0 -1.084551 -0.293405 -0.402948       NaN
1 -1.543618 -0.403538  0.340821       NaN
2  0.295654 -0.754895  1.932140       NaN
3  0.387930 -0.397124 -0.430610       NaN
4 -1.050797  1.380461       NaN  0.465284
5 -1.216634 -0.397843       NaN -0.110875
6  0.209350  0.353455       NaN -0.482835

In [ ]:
url =