In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [4]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [7]:
A = np.random.randn(10)

In [8]:
A

array([-1.85515342, -0.55187921, -0.07383584, -1.05017188,  0.90826837,
        0.51637766, -1.52739301,  0.98154323,  1.64344186,  0.28262969])

In [9]:
B = np.random.randn(10)
B

array([ 0.04316588, -0.69322804, -1.65994748,  1.5455968 , -1.3139355 ,
        0.63916871,  0.26242547,  1.43762158, -0.16060896,  0.12655155])

In [10]:
# Binary Functions
np.add(A,B)

array([-1.81198754, -1.24510726, -1.73378331,  0.49542492, -0.40566713,
        1.15554637, -1.26496753,  2.41916482,  1.48283291,  0.40918124])

In [11]:
np.maximum(A,B)

array([ 0.04316588, -0.55187921, -0.07383584,  1.5455968 ,  0.90826837,
        0.63916871,  0.26242547,  1.43762158,  1.64344186,  0.28262969])